version: '3.7'

services:

  database:
    image: "postgres:13.4-alpine"
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  core:
    image: "cunningbird/core:0.0.3"
    container_name: core
    build:
      context: core
    ports:
      - "8077:8077"
    depends_on:
      - database
    environment:
      - SPRING_APPLICATION_PORT=8077
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/core
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

  gateway-customer:
    image: "cunningbird/gateway-customer:0.0.1"
    container_name: gateway-customer
    build:
      context: gateway/customer
    ports:
      - "8078:8078"
    links:
      - identity
      - core
    depends_on:
      - identity
      - core
    environment:
      - SPRING_APPLICATION_PORT=8078
      - SPRING_JWT_ISSUER_URI=http://identity:8080
      - SPRING_BACKEND_URI=http://core:8077

  gateway-executor:
    image: "cunningbird/gateway-executor:0.0.1"
    container_name: gateway-executor
    build:
      context: gateway/executor
    ports:
      - "8079:8079"
    links:
      - identity
      - core
    depends_on:
      - identity
      - core
    environment:
      - SPRING_APPLICATION_PORT=8079
      - SPRING_JWT_ISSUER_URI=http://identity:8080
      - SPRING_BACKEND_URI=http://core:8077

  identity:
    image: "cunningbird/identity:0.0.1"
    container_name: identity
    build:
      context: identity
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_APPLICATION_PORT=8080
      - SPRING_PUBLIC_ISSUER_URI=http://identity:8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/identity
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password

volumes:
  postgres-data: