server:
  port: ${SPRING_APPLICATION_PORT}

spring:
  application:
    name: identity
  main:
    banner-mode: off
  security:
    oauth2:
      authorizationserver:
        provider-name: ${SPRING_PUBLIC_ISSUER_URI}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    schemas: public
    locations:
      - classpath:db/postgres/migration