server:
  port: ${SPRING_APPLICATION_PORT}

spring:
  application:
    name: gateway-executor
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_JWT_ISSUER_URI}
  cloud:
    gateway:
      routes:
        - id: bfb
          uri: ${SPRING_BACKEND_URI}
          predicates:
            - Path=/**